name: "Continuous Integration"
run-name: "Unit testing for continuous integration"
on: [push]
defaults:
  run:
    working-directory: ./iac/live
jobs:
  terra-ci-ut:
    name: "Unit test for terraform code"
    runs-on: ubuntu-latest
    steps:
      # repository checkout
      - name: Checkout
        uses: actions/checkout@v3

      # install terraform cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # initialize working directory containing Terraform configuration files
      - name: Terraform Init
        run: terraform init

      # validate configuration files
      - name: Terraform Validate
        run: terraform validate

      # check formatting of configuration files
      - name: Terraform Format
        run: terraform fmt -check -recursive
