name: "Continuous Integration"
run-name: "Unit testing for continuous integration"
on: [push]
defaults:
  run:
    working-directory: ./iac/live
# specify environment variables
env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"
jobs:
  terra-ci-ut:
    name: "Unit Testing"
    runs-on: ubuntu-latest
    steps:
      # repository checkout
      - name: Checkout
        uses: actions/checkout@v3

      # install terraform cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # initialize working directory containing Terraform configuration files
      - name: Terraform Init
        run: terraform init

      # validate configuration files
      - name: Terraform Validate
        run: terraform validate

      # check formatting of configuration files
      - name: Terraform Format
        run: terraform fmt -check -recursive
